export default {
    FETCH_DIRECTORY_CONTENTS_STARTED: 'FETCH_DIRECTORY_CONTENTS_STARTED',
    FETCH_DIRECTORY_CONTENTS_SUCCESS: 'FETCH_DIRECTORY_CONTENTS_SUCCESS',
    FETCH_DIRECTORY_CONTENTS_FAILURE: 'FETCH_DIRECTORY_CONTENTS_FAILURE',
    FETCH_DIRECTORY_CONTENTS_ENDED: 'FETCH_DIRECTORY_CONTENTS_ENDED',
};
