export default {
    FETCH_DIRECTORY_CONTENTS_STARTED: 'FETCH_DIRECTORY_CONTENTS_STARTED',
    FETCH_DIRECTORY_CONTENTS_SUCCESS: 'FETCH_DIRECTORY_CONTENTS_SUCCESS',
    FETCH_DIRECTORY_CONTENTS_FAILURE: 'FETCH_DIRECTORY_CONTENTS_FAILURE',
    FETCH_DIRECTORY_CONTENTS_ENDED: 'FETCH_DIRECTORY_CONTENTS_ENDED',

    CREATE_DIRECTORY_STARTED: 'CREATE_DIRECTORY_STARTED',
    CREATE_DIRECTORY_SUCCESS: 'CREATE_DIRECTORY_SUCCESS',
    CREATE_DIRECTORY_FAILURE: 'CREATE_DIRECTORY_FAILURE',
    CREATE_DIRECTORY_ENDED: 'CREATE_DIRECTORY_ENDED',

    DELETE_FILE_STARTED: 'DELETE_FILE_STARTED',
    DELETE_FILE_SUCCESS: 'DELETE_FILE_SUCCESS',
    DELETE_FILE_FAILURE: 'DELETE_FILE_FAILURE',
    DELETE_FILE_ENDED: 'DELETE_FILE_ENDED',

    RENAME_FILE_STARTED: 'RENAME_FILE_STARTED',
    RENAME_FILE_SUCCESS: 'RENAME_FILE_SUCCESS',
    RENAME_FILE_FAILURE: 'RENAME_FILE_FAILURE',
    RENAME_FILE_ENDED: 'RENAME_FILE_ENDED',

    FETCH_PASSWORD_CONTENTS_STARTED: 'FETCH_PASSWORD_CONTENTS_STARTED',
    FETCH_PASSWORD_CONTENTS_SUCCESS: 'FETCH_PASSWORD_CONTENTS_SUCCESS',
    FETCH_PASSWORD_CONTENTS_FAILURE: 'FETCH_PASSWORD_CONTENTS_FAILURE',
    FETCH_PASSWORD_CONTENTS_ENDED: 'FETCH_PASSWORD_CONTENTS_ENDED',

    SAVE_PASSWORD_STARTED: 'SAVE_PASSWORD_STARTED',
    SAVE_PASSWORD_SUCCESS: 'SAVE_PASSWORD_SUCCESS',
    SAVE_PASSWORD_FAILURE: 'SAVE_PASSWORD_FAILURE',
    SAVE_PASSWORD_ENDED: 'SAVE_PASSWORD_ENDED',
};
