export default {
    FETCH_DIRECTORY_CONTENTS_STARTED: 'FETCH_DIRECTORY_CONTENTS_STARTED',
    FETCH_DIRECTORY_CONTENTS_SUCCESS: 'FETCH_DIRECTORY_CONTENTS_SUCCESS',
    FETCH_DIRECTORY_CONTENTS_FAILURE: 'FETCH_DIRECTORY_CONTENTS_FAILURE',
    FETCH_DIRECTORY_CONTENTS_ENDED: 'FETCH_DIRECTORY_CONTENTS_ENDED',

    FETCH_PASSWORD_CONTENTS_STARTED: 'FETCH_PASSWORD_CONTENTS_STARTED',
    FETCH_PASSWORD_CONTENTS_SUCCESS: 'FETCH_PASSWORD_CONTENTS_SUCCESS',
    FETCH_PASSWORD_CONTENTS_FAILURE: 'FETCH_PASSWORD_CONTENTS_FAILURE',
    FETCH_PASSWORD_CONTENTS_ENDED: 'FETCH_PASSWORD_CONTENTS_ENDED',

    CREATE_PASSWORD_STARTED: 'CREATE_PASSWORD_STARTED',
    CREATE_PASSWORD_SUCCESS: 'CREATE_PASSWORD_SUCCESS',
    CREATE_PASSWORD_FAILURE: 'CREATE_PASSWORD_FAILURE',
    CREATE_PASSWORD_ENDED: 'CREATE_PASSWORD_ENDED',
};
